jobs:
  - name: assemble
    type: runSh
    steps:
     - IN: ryvr-jobs_master_rSync
     - IN: ryvr_source
       showBuildStatus: true 
     - TASK: 
       - script: cd ./IN/ryvr_source/gitRepo/ && ./gradlew assemble --info

  - name: unitTest
    type: runSh
    steps:
     - IN: assemble
     - IN: ryvr_source
       showBuildStatus: true 
     - TASK: 
       - script: cd ./IN/ryvr_source/gitRepo/ && ./gradlew unitTest -x jacocoTestReport --info 
     - OUT: unit-test-report